sushi-site-work/sushi-site-work/Controllers/CheckoutController.cs
using sushi_site_work.Models;
using System;
using System.Linq;
using System.Web.Mvc;
using System.Data.Entity;


namespace sushi_site_work.Controllers
{
    [Authorize]
    public class CheckoutController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        const string PromoCode = "SUSHI";

        //
        // GET: /Checkout/AddressAndPayment
        public ActionResult AddressAndPayment()
        {
            return View();
        }
        //
        // POST: /Checkout/AddressAndPayment
        [HttpPost]
        public ActionResult AddressAndPayment(FormCollection values)
        {
            var order = new Order();
            TryUpdateModel(order);

            try
            {
                if (string.Equals(values["PromoCode"], PromoCode,
                    StringComparison.OrdinalIgnoreCase) == false)
                {
                    return View(order);
                }
                else
                {
                    order.Username = User.Identity.Name;
                    order.OrderDate = DateTime.Now;

                    //Save Order
                    db.Orders.Add(order);
                    db.SaveChanges();
                    //Process the order
                    var cart = ShoppingCart.GetCart(this.HttpContext);
                    cart.CreateOrder(order);

                    return RedirectToAction("Complete",
                        new { id = order.OrderId });
                }
            }
            catch
            {
                //Invalid - redisplay with errors
                return View(order);
            }
        }
        //
        // GET: /Checkout/Complete
        public ActionResult Complete(int id)
        {
            // Validate customer owns this order
            bool isValid = db.Orders.Any(
                o => o.OrderId == id &&
                o.Username == User.Identity.Name);

            if (isValid)
            {
                return View(id);
            }
            else
            {
                return View("Error");
            }
        }
    }
}

sushi-site-work/sushi-site-work/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using sushi_site_work.Models;


namespace sushi_site_work.Controllers
{
    public class ShoppingCartController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: ShoppingCart
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            // Return the view
            return View(viewModel);
        }
        //
        // GET: /Store/AddToCart/5
        public ActionResult AddToCart(int id)
        {
            // Retrieve the album from the database
            var addedProduct = db.products
                .Single(product => product.Id == id);

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            cart.AddToCart(addedProduct);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }
        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the name of the album to display confirmation
            string productName = db.Carts
                .Single(item => item.RecordId == id).Product.Name;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(productName) +
                    " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }
        //
        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }

    }
}

sushi-site-work/sushi-site-work/Controllers/StoreController.cs
using sushi_site_work.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;


namespace sushi_site_work.Controllers
{
    public class StoreController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        //
        // GET: /Store/
        public ActionResult Index()
        {
            var subCategory = db.subCategories.ToList();
            return View(subCategory);
        }
        //
        // GET: /Store/Browse
        public ActionResult Browse(string subCategories)
        {
            // Retrieve Genre and its Associated Albums from database
            var subCategoriesModel = db.subCategories.Include("Products").Single(g => g.Name == subCategories);

            return View(subCategoriesModel);
        }

        // GET: /Store/Details
        public ActionResult Details(int id)
        {
            var product = db.products.Find(id);

            return View(product);
        }

        //
        // GET: /Store/SubCategoriesMenu
        [ChildActionOnly]
        public ActionResult SubCategoriesMenu()
        {
            var subCategories = db.subCategories.ToList();
            return PartialView(subCategories);
        }
       
    }
}

sushi-site-work/sushi-site-work/Views/ShoppingCart/CartSummary.cshtml
@{
    ViewBag.Title = "Cart Summary";
}
<div class="d-flex justify-content-endt">
    <div class="p-2 bd-highlight">
        @Html.ActionLink("Кошик (" + ViewData["CartCount"] + ")", "Index", "ShoppingCart", new { id = "cart-status" })
</div>
    </div>

sushi-site-work/sushi-site-work/Views/ShoppingCart/Index.cshtml
@model sushi_site_work.Models.ShoppingCartViewModel
@{
    ViewBag.Title = "Index";
}
<script src="/Scripts/jquery-3.5.1.min.js" type="text/javascript"></script>
<script type="text/javascript">
    $(function () {
        // Document.ready -> link up remove event handler
        $(".RemoveLink").click(function () {
            // Get the id from the link
            var recordToDelete = $(this).attr("data-id");
            if (recordToDelete != '') {
                // Perform the ajax post
                $.post("/ShoppingCart/RemoveFromCart", { "id": recordToDelete },
                    function (data) {
                        // Successful requests get here
                        // Update the page elements
                        if (data.ItemCount == 0) {
                            $('#row-' + data.DeleteId).fadeOut('slow');
                        } else {
                            $('#item-count-' + data.DeleteId).text(data.ItemCount);
                        }
                        $('#cart-total').text(data.CartTotal);
                        $('#update-message').text(data.Message);
                        $('#cart-status').text('Cart (' + data.CartCount + ')');
                    });
            }
        });
    });
</script>

<div class="card-body">
    <h3 class="text-md-center text-warning font-weight-bold">У Вашому кошику:</h3>
</div>


<table class="table">
    <thead class="thead-dark">
        <tr>
            <th scope="col">
                Продукти
            </th>
            <th scope="col">
                Вартість
            </th>
            <th scope="col">
                Кількість
            </th>
            <th scope="col">
            </th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model.CartItems)
        {
            <tr>
                <th scope="row-@item.RecordId">
                    @Html.ActionLink(item.Product.Name, "Details", "Store", new { id = item.ProductId }, null)
                </th>
                <td>
                    @item.Product.Cost
                </td>
                <td id="item-count-@item.RecordId">
                    @item.Count
                </td>
                <td>
                    <a href="#" class="RemoveLink" data-id="@item.RecordId">
                        Видалити
                    </a>
                </td>
            </tr>
        }
    <thead class="thead-light">
        <tr>

            <th scope="col">
                Загальна сума
            </th>
            <th scope="col">
            </th>
            <th scope="col">
            </th>
            <th scope="col">
                @Model.CartTotal
            </th>
        </tr>
        </thead>
    <tbody>

</table>

<div class="align-content-center">
    <button type="button" class="btn btn-warning  align-items-sm-center  btn-block" style="margin:auto; width:300px;">
        <a class="font-weight-bolder">
            @Html.ActionLink("Замовити", "AddressAndPayment", "Checkout")
        </a>
    </button>
</div>